// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZr0m1xSpJ_WChAFfmlGWcLWJ5hhVa824',
    appId: '1:573392308226:web:6fbc894a31354644a43f1b',
    messagingSenderId: '573392308226',
    projectId: 'fire-note-10',
    authDomain: 'fire-note-10.firebaseapp.com',
    storageBucket: 'fire-note-10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKpjycG_RE6joY5nQacNdW4JDWXtl5w_k',
    appId: '1:573392308226:android:ce246ba8fe609c24a43f1b',
    messagingSenderId: '573392308226',
    projectId: 'fire-note-10',
    storageBucket: 'fire-note-10.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGWaqkL-LhhCSjm_JTNAr33Ptnl0eKAQk',
    appId: '1:573392308226:ios:b96f383ddb7638eea43f1b',
    messagingSenderId: '573392308226',
    projectId: 'fire-note-10',
    storageBucket: 'fire-note-10.firebasestorage.app',
    iosBundleId: 'com.example.fireNoteCohort10',
  );
}
